feat: `Joints` implementation
Tresjs/rapier pull request #150
Opened 2024-11-20 00:16 UTC by Neosoulink

## Summary

This PR introduces the [Joints](https://rapier.rs/docs/user_guides/javascript/joints/) feature.

Joints are one of the advanced features natively available in `Rapier`.
This PR provides an easy, basic but robust way to deal with it.

### Logs

- Support for all the supported Joint types
  - `"fixed" | "spring" | "rope" | "generic" | "spherical" | "prismatic" | "revolute"`
- New components based on the supported joint types (`FixedJoint`, `SphericalJoint`, ...)

### How to use

Here's a basic implementation example:
```vue
<RigidBody
  v-for="(ref, i) in bodyRefs"
  :key="i"
  :ref="ref"
  :type="i === 0 ? 'kinematic' : 'dynamic'"
  :position="[i * 1.5, 0, 0]"
   collider="ball"
 >
  <TresMesh>
    <TresSphereGeometry />
    <TresMeshNormalMaterial />
  </TresMesh>
</RigidBody>

<SphericalJoint
  v-for="(ref, i) in bodyRefs"
  :key="i"
  :bodies="[ref.value?.[0]?.instance, bodyRefs[i - 1]?.value?.[0]?.instance]"
  :params="[
    [-1.1, 0, 0],
    [1.1, 0, 0],
  ]"
/>
```
> Preview

https://github.com/user-attachments/assets/e30dc274-597f-4903-bcc6-4060711e5494

### TODO: implement a decent documentation

2024-12-09 14:08 UTC, Neosoulink commented
Hi @alvarosabu, I just added a base documentation for `Joint`.
I'd appreciate having your review of it (the `Joint` implementation in general).

cc: @JaimeTorrealba

2025-01-07 17:56 UTC, Neosoulink commented
Any update on this one?

> This PR is waiting for review

2025-01-11 19:11 UTC, JaimeTorrealba requested changes
I like the implementation, But also I would add a composable WDYT? With the same logic

an `useJoint()` or similar so the people is not force to use it with Tres.js components only

2025-01-11 19:11 UTC, JaimeTorrealba commented on .vscode/settings.json
> +  "cSpell.words": [
I think the settings should be removed here, this is personal to our environments.

2025-01-11 19:11 UTC, JaimeTorrealba commented on docs/components/joint.md
> +In **Tres** we can achieve such motion restriction by using one of the available components designed to handle joints:
Small one but maybe we need consistency here it all pages should be "Tres.js"

2025-01-11 19:11 UTC, JaimeTorrealba commented on docs/components/joint.md
> +    v-for="(ref, i) in bodyRefs"
I got a problem, the mental load of this example is high. I would instead, in this page, come with a very basic example, just two rigid Bodies joined (just that). The idea here is that they learn how to use it.

2025-01-11 19:11 UTC, JaimeTorrealba commented on playground/src/pages/basics/JointsDemo.vue
> +setInterval(() => {
Why setInterval?

And if you decided to use setInterval, please remember to clear the interval in the onUnmouted

2025-01-11 19:13 UTC, JaimeTorrealba commented on src/components/joints/BaseJoint.vue
> +    throw new Error(`Invalid "${type}" joint parameters`)
Maybe too difficult, but could be said what parameters have problems?

2025-01-11 21:10 UTC, Neosoulink commented on .vscode/settings.json
> +  "cSpell.words": [
got it ✅

2025-01-11 21:10 UTC, Neosoulink commented on docs/components/joint.md
> +In **Tres** we can achieve such motion restriction by using one of the available components designed to handle joints:
Noted

2025-01-11 21:15 UTC, Neosoulink commented on playground/src/pages/basics/JointsDemo.vue
> +setInterval(() => {
Oh yeah, you're right,

`setInterval` was used to update the rotation of the first and have that whip effect

2025-01-11 21:17 UTC, Neosoulink commented
> I like the implementation, But also I would add a composable WDYT? With the same logic
> 
> an `useJoint()` or similar so the people is not force to use it with Tres.js components only

I think it possible even to have both features

2025-01-11 21:32 UTC, JaimeTorrealba commented
> > I like the implementation, But also I would add a composable WDYT? With the same logic
> > an `useJoint()` or similar so the people is not force to use it with Tres.js components only
> 
> I think it possible even to have both features

Completely, maybe another PR to be more organized.

2025-01-13 12:25 UTC, Neosoulink commented on docs/components/joint.md
> +    v-for="(ref, i) in bodyRefs"
This example reflects the one in the playground (the `JointsDemo` example)...
Is it okay to simplify this one in this documentation but keep the demo as it is?

2025-01-13 13:35 UTC, Neosoulink commented on src/components/joints/BaseJoint.vue
> +    throw new Error(`Invalid "${type}" joint parameters`)
Sure, maybe a string containing the requirement or why it the error occurs

2025-01-13 19:03 UTC, Neosoulink commented
> Completely, maybe another PR to be more organized.

I pushed the changes requested, and yes, this will be part of a separate PR ✅

#### Here what has changed:
- [c1a6ffd1769b6a872c48a42bcd54bf02333658e1](https://github.com/Tresjs/rapier/pull/150/commits/c1a6ffd1769b6a872c48a42bcd54bf02333658e1)
  - Make the Joint component listen to updates
  - Provide more precise `Joint` error messages
  - Simplify the Joint example and the Joint documentation
  - Remove `cSpell.words` VsCode setting

2025-01-13 19:11 UTC, JaimeTorrealba approved these changes

2025-01-20 15:30 UTC, alvarosabu requested changes

2025-01-20 15:33 UTC, Neosoulink commented on docs/components/joint.md
> +<script setup>
Got it

2025-01-20 15:33 UTC, Neosoulink commented on docs/components/joint.md
Noted

2025-01-20 15:35 UTC, Neosoulink commented on docs/components/joint.md
> +<img width="1141" alt="JointsDemo" src="https://github.com/user-attachments/assets/d3cacac3-8764-4906-886a-d0b7a764b7c0" />
It was automatically added from github, but let make it clean. I'm going to update it

2025-01-20 15:47 UTC, Neosoulink commented on src/components/joints/index.ts
This approach priorities re-usability based on the same component.
In other words, it's just a shortcut for the `Joints`

It's exactly the same as doing:

```tsx
<Joint type="joint-type" />
```

> It's a pattern I often used to implement a few years ago back in 2019 (old goods days 🥲)
> It's a pattern I discovered while learning how Vue was working under the hood

2025-01-27 20:06 UTC, Neosoulink commented on src/components/joints/index.ts
Hey!
While updating it, I realized I did the same for the `Colliders`, Why not make the change on a separate PR, to update the pattern? (for `Joints` & `Colliders`)

2025-03-18 09:47 UTC, alvarosabu approved these changes

2025-03-18 09:47 UTC, merged